config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|tr/ do
    devise_for :users, controllers: {
      sessions: "users/authentication/sessions",
      registrations: "users/authentication/registrations"
    }

    devise_scope :user do
      get "profile", to: "users/authentication/registrations#show", as: "user_profile"
      get "/users/sign_out" => "users/authentication/sessions#destroy"
    end

    root "articles#index"

    resources :articles do
      resources :likes, only: [ :create, :destroy ]
      resources :recommendations, only: [ :create, :new ]
      resources :comments, only: [ :create, :destroy ]
      collection do
        get "search", to: "articles#search"
      end
    end

    resources :notifications, only: [ :index ] do
      member do
        post :mark_as_read
      end
    end

    resources :tags, only: [ :index, :show ]

    get "categories", to: "pages#categories"
    get "about", to: "pages#about"
    get "contact", to: "pages#contact"

    get "recommendations", to: "recommendations#index", as: "recommendations"
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible

  belongs_to :article
  belongs_to :user

  validates :content, presence: true

  before_validation :set_default_status
  after_create_commit :send_notification_to_article_author
  after_destroy_commit :remove_notification

  private

  def set_default_status
    self.status ||= "public"
  end

  def send_notification_to_article_author
    return if user == article.user

    Notification.create!(
      user: article.user,
      notifiable: self
    )
  end

  def remove_notification
    Notification.find_by(notifiable: self)&.destroy
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article
  before_action :authenticate_user!

  def create
    @comment = @article.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      respond_to do |format|
        format.html { redirect_to @article, notice: "Comment was successfully added." }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace("comment_form", partial: "comments/form", locals: { article: @article, comment: @comment })
        end
        format.html { redirect_to @article, alert: "Comment could not be saved." }
      end
    end
  end

  def destroy
    @comment = @article.comments.find(params[:id])

    if @comment.destroy
      respond_to do |format|
        format.html { redirect_to @article, notice: "Comment was successfully deleted." }
        format.turbo_stream
      end
    else
      respond_to do |format|
        format.html { redirect_to @article, alert: "Comment could not be deleted." }
        format.turbo_stream { head :unprocessable_entity }
      end
    end
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="comment_<%= comment.id %>" class="p-5 bg-white rounded-lg border border-gray-200 shadow-sm hover:shadow-md transition duration-150 mb-4">
  <div class="flex items-start space-x-4">
    <div class="flex-shrink-0">
      <div class="w-10 h-10 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center text-white font-bold text-sm">
        <%= comment.user.first_name[0].upcase + comment.user.last_name[0].upcase %>
      </div>
    </div>
    
    <div class="flex-1 min-w-0">
      <div class="flex items-center justify-between mb-1">
        <p class="text-gray-900 font-medium"><%= comment.user.full_name %></p>
        <p class="text-gray-500 text-xs"><%= comment.created_at.strftime("%b %d, %Y · %H:%M") %></p>
      </div>
      
      <div class="prose prose-sm max-w-none text-gray-700 mb-3">
        <%= comment.content %>
      </div>
      
      <div class="flex items-center space-x-4 mt-2">
        <button class="text-gray-500 hover:text-gray-700 text-sm flex items-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14 10h4.764a2 2 0 011.789 2.894l-3.5 7A2 2 0 0115.263 21h-4.017c-.163 0-.326-.02-.485-.06L7 20m7-10V5a2 2 0 00-2-2h-.095c-.5 0-.905.405-.905.905 0 .714-.211 1.412-.608 2.006L7 11v9m7-10h-2M7 20H5a2 2 0 01-2-2v-6a2 2 0 012-2h2.5" />
          </svg>
          Like
        </button>
        
        <button class="text-gray-500 hover:text-gray-700 text-sm flex items-center">
          <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 12h.01M12 12h.01M16 12h.01M21 12c0 4.418-4.03 8-9 8a9.863 9.863 0 01-4.255-.949L3 20l1.395-3.72C3.512 15.042 3 13.574 3 12c0-4.418 4.03-8 9-8s9 3.582 9 8z" />
          </svg>
          Reply
        </button>
        
        <% if comment.user == current_user %>
          <%= link_to article_comment_path(comment.article, comment), 
              data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this comment?" }, 
              class: "text-red-500 hover:text-red-700 text-sm flex items-center ml-auto" do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 mr-1" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
            </svg>
            Delete
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@article, Comment.new], url: article_comments_path(@article), method: :post, data: { turbo_frame: "comments" }) do |f| %>
  <% if @comment&.errors&.any? %>
    <div class="bg-red-50 border-l-4 border-red-500 p-4 mb-6 rounded-md">
      <div class="flex items-start">
        <div class="flex-shrink-0">
          <svg class="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd" />
          </svg>
        </div>
        <div class="ml-3">
          <h3 class="text-sm font-medium text-red-800">
            <%= pluralize(@comment.errors.count, "error") %> prevented this comment from being saved:
          </h3>
          <div class="mt-2 text-sm text-red-700">
            <ul class="list-disc pl-5 space-y-1">
              <% @comment.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class="flex items-start space-x-4">
    <div class="flex-shrink-0">
      <div class="w-10 h-10 rounded-full bg-gradient-to-br from-blue-500 to-purple-600 flex items-center justify-center text-white font-bold text-sm">
        <%= current_user.first_name[0].upcase + current_user.last_name[0].upcase rescue "YO" %>
      </div>
    </div>
    
    <div class="min-w-0 flex-1">
      <div class="relative">
        <%= f.text_area :content, 
            rows: 3, 
            placeholder: "Write a comment...", 
            class: "block w-full rounded-lg border border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500 sm:text-sm px-4 py-3 placeholder-gray-400" %>
      </div>
      
      <div class="mt-3 flex items-center justify-between">
        <div class="flex items-center space-x-5">
          <button type="button" class="rounded-full p-1 text-gray-500 hover:text-gray-600">
            <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
          </button>
          <button type="button" class="rounded-full p-1 text-gray-500 hover:text-gray-600">
            <svg class="h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13" />
            </svg>
          </button>
        </div>
        
        <%= f.button type: "submit", class: "inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" do %>
          <svg class="h-4 w-4 mr-1.5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8" />
          </svg>
          Send
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<turbo-stream action="append" target="comments">
  <template>
    <%= render partial: "comments/comment", formats: [:html], locals: { comment: @comment } %>
  </template>
</turbo-stream>

app/views/comments/destroy.turbo_stream.erb
<turbo-stream action="remove" target="comment_<%= @comment.id %>"></turbo-stream>