config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|tr/ do
    devise_for :users, controllers: {
      sessions: "users/authentication/sessions",
      registrations: "users/authentication/registrations"
    }

    devise_scope :user do
      get "profile", to: "users/authentication/registrations#show", as: "user_profile"
      get "/users/sign_out" => "users/authentication/sessions#destroy"
    end

    root "articles#index"

    resources :articles do
      resources :likes, only: [ :create, :destroy ]
      resources :recommendations, only: [ :create, :new ]
      resources :comments, only: [ :create, :destroy ]
      collection do
        get "search", to: "articles#search"
      end
    end

    resources :notifications, only: [ :index ] do
      member do
        post :mark_as_read
      end
    end

    resources :tags, only: [ :index, :show ]

    get "categories", to: "pages#categories"
    get "about", to: "pages#about"
    get "contact", to: "pages#contact"

    get "recommendations", to: "recommendations#index", as: "recommendations"
  end
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible

  scope :not_archived, -> { where.not(status: "archived") }
  scope :published, -> { where("publish_at IS NULL OR publish_at <= ?", Time.current) }

  after_commit :schedule_publish, on: [ :create, :update ]

  def scheduled?
    publish_at.present? && publish_at > Time.current
  end

  private

  def schedule_publish
    if scheduled? && publish_at.present? && id.present?
      PublishArticleJob.set(wait_until: publish_at).perform_later(id)
    end
  end



  has_many :comments, dependent: :destroy
  has_one_attached :image

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  belongs_to :user
  has_many :recommendations, dependent: :destroy
  has_many :recommended_users, through: :recommendations, source: :recommended_user

  has_many :article_tags, dependent: :destroy
  has_many :tags, through: :article_tags

  accepts_nested_attributes_for :tags, allow_destroy: true

  has_rich_text :body

  has_many :likes
  has_many :liked_users, through: :likes, source: :user

  def self.ransackable_attributes(auth_object = nil)
    [ "id", "title", "body", "status", "publish_at" ]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include SetArticle
  include Authorization

  before_action :authenticate_user!
  before_action :set_article, only: [ :show, :edit, :update, :destroy ]

  def index
    @query = Article.not_archived.ransack(params[:query])
    @pagy, @articles = pagy(@query.result(distinct: true), items: 10)
    Rails.logger.debug "Articles from index: #{@articles.map(&:title).inspect}"
  end

  def search
    @query = Article.ransack(params[:query])
    Rails.logger.debug "Ransack query: #{@query.inspect}"
    @pagy, @articles = pagy(@query.result(distinct: true))
    Rails.logger.debug "Articles found: #{@articles.map(&:title).inspect}"
    render :index
  end

  def show
    if @article.nil?
      redirect_to articles_path, alert: "Article not found." and return
    end
    @recommendation = Recommendation.new(article: @article)
    render :show, layout: "article_show"
  end

  def new
    @article = Article.new
    @article.tags.build
  end

  def create
    @article = current_user.articles.new(article_params)
    if params[:article][:schedule_publish] == "1" && params[:article][:publish_at].present?
      @article.publish_at = Time.zone.parse(params[:article][:publish_at])
      @article.status = "scheduled"
    else
      @article.publish_at = nil
      @article.status = "public"
    end

    if @article.save
      notice_message = @article.scheduled? ? "Makale planlandı, belirtilen tarihte yayınlanacak." : "Makale başarıyla oluşturuldu."
      respond_to do |format|
        format.html { redirect_to article_path(@article), notice: notice_message }
        format.turbo_stream { render turbo_stream: view_context.turbo_notification(notice_message) }
      end
    else
      render :new, alert: "Makale oluşturulamadı"
    end
  end




  def edit
  end

  def update
    if @article.update(article_params)
      notice_message = "Makale başarıyla güncellendi."
      respond_to do |format|
        format.html { redirect_to article_path(@article), notice: notice_message }
        format.turbo_stream { render turbo_stream: view_context.turbo_notification(notice_message) }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article.destroy
    notice_message = "Makale başarıyla silindi."
    respond_to do |format|
      format.html { redirect_to articles_path, status: :see_other, notice: notice_message }
      format.turbo_stream { render turbo_stream: view_context.turbo_notification(notice_message) }
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :status, :image, :publish_at, tag_ids: [])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true, url: article_path(@article)) do |form| %>
    <section>
        <% if article.errors.any? %>
            <div class="bg-red-100 text-red-800 p-4 rounded-lg mb-4">
                <ul>
                    <% article.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                </ul>
            </div>
        <% end %>
    </section>

    <section class="mb-4">
        <%= form.label :title, class: "block text-sm font-medium text-gray-700" %>
        <%= form.text_field :title, class: "h-12 px-4 border border-gray-300 rounded-md w-full text-gray-700 placeholder-gray-500 focus:ring-2 focus:ring-primary focus:outline-none" %>
    </section>

    <div class="mb-4">
        <%= form.label :body, class: "block text-sm font-semibold text-gray-700 mb-2" %>
        <%= form.rich_text_area :body, class: "h-48 px-4 border border-gray-300 rounded-md w-full text-gray-700 placeholder-gray-500 focus:ring-2 focus:ring-primary-50 focus:outline-none" %>

    </div>

    <section class="mb-4">
        <%= form.label :status, class: "block text-sm font-medium text-gray-700" %>
        <%= form.select :status, 
          Visible.VALID_STATUSES.map { |status| [t("visible.valid_statuses.#{status}"), status] }, 
          { selected: @article.status || 'public' }, 
          class: "h-12 px-4 border border-gray-300 rounded-md w-full text-gray-700 placeholder-gray-500 focus:ring-2 focus:ring-primary-50 focus:outline-none" %>
    </section>

    <div class="mb-4">
        <%= form.label :tag_ids, "Etiketler", class: "block text-sm font-semibold text-gray-700 mb-2" %>
        <%= form.collection_select :tag_ids, Tag.all, :id, :name, 
      { include_blank: false }, 
      { multiple: true, size: 5, class: "px-4 border border-gray-300 rounded-md w-full text-gray-700 focus:ring-2 focus:ring-primary-50 focus:outline-none" } %>
    </div>

    <div class="mb-4">
        <%= form.label :image, "Kapak Fotoğrafı", class: "block text-sm font-semibold text-gray-700 mb-2" %>
        <%= form.file_field :image, class: "block w-full text-gray-700 border border-gray-300 rounded-md cursor-pointer focus:ring-2 focus:ring-primary-50 focus:outline-none" %>

        <% if @article.image.attached? %>
            <p class="text-sm text-gray-500 mt-2">Mevcut Görsel:</p>
            <%= image_tag @article.image, class: "w-full h-48 object-cover rounded-lg shadow-md mt-2" %>
        <% end %>
    </div>

    <section class="flex justify-end">
        <%= form.submit "Save Changes", class: "w-full bg-primary-500 text-white font-bold py-2 rounded-lg hover:bg-primary-600 focus:outline-none focus:ring-2 focus:ring-primary-700 transition duration-200" %>
    </section>
<% end %>

app/views/articles/_like_button.html.erb
<div id="article_<%= article.id %>_like_button" class="inline-block">
    <% if article.likes.exists?(user: current_user) %>
        <%= button_to article_like_path(article, article.likes.find_by(user: current_user)), 
                  method: :delete, 
                  remote: true,
                  class: "flex items-center space-x-1 px-3 py-2 bg-red-100 hover:bg-red-200 text-red-600 rounded-full transition duration-200 focus:outline-none focus:ring-2 focus:ring-red-400" do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 24 24" fill="currentColor" stroke="none">
                <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path>
            </svg>
            <span>Beğeniyi Kaldır</span>
        <% end %>
    <% else %>
        <%= button_to article_likes_path(article), 
                  method: :post, 
                  remote: true,
                  class: "flex items-center space-x-1 px-3 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-full transition duration-200 focus:outline-none focus:ring-2 focus:ring-gray-400" do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path>
            </svg>
            <span>Like</span>
        <% end %>
    <% end %>
</div>

app/views/articles/_like_count.html.erb
<span id="article_<%= article.id %>_likes_count" class="inline-flex items-center text-gray-600 bg-gray-50 px-2 py-1 rounded-md text-sm">
    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-red-500 mr-1" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M3.172 5.172a4 4 0 015.656 0L10 6.343l1.172-1.171a4 4 0 115.656 5.656L10 17.657l-6.828-6.829a4 4 0 010-5.656z" clip-rule="evenodd"/>
    </svg>
    <strong><%= article.likes.count %></strong>
    <span class="ml-1">Likes</span>
</span>

app/views/articles/_list.html.erb
<turbo-frame id="articles_frame">

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <% articles.each do |article| %>
            <%= link_to article_path(article), data: { turbo_frame: "_top" }, class: "block h-full" do %>
                <div class="article bg-secondary-50 shadow-md rounded-lg overflow-hidden transition duration-300 hover:shadow-xl h-full flex flex-col">
                    <% if article.image.attached? %>
                        <%= image_tag article.image, class: "w-full h-48 object-cover" %>
                    <% else %>
                        <div class="w-full h-48 bg-purple-200 flex items-center justify-center">
                            <span class="text-primary-600">No Image</span>
                        </div>
                    <% end %>
                    <div class="p-6 flex-grow bg-gradient-to-b from-secondary-50 to-primary-50">
                        <h3 class="text-xl font-semibold mb-2 text-secondary-800 hover:text-primary-600 transition duration-200">
                            <%= article.title %>
                        </h3>
                        <p class="text-secondary-600 text-sm">
                            <%= article.body.to_plain_text.truncate(100) %>
                        </p>
                    </div>
                    <div class="px-6 py-4 bg-primary-100">
                        <span class="inline-block bg-primary-200 rounded-full px-3 py-1 text-sm font-semibold text-primary-700 mr-2">
                            <%= article.created_at.strftime("%B %d, %Y") %>
                        </span>
                    </div>
                </div>
            <% end %>
        <% end %>
    </div>
</turbo-frame>

app/views/articles/_search.html.erb
<%= search_form_for @query, url: search_articles_path, method: :get, data: { turbo_frame: "articles" } do |form| %>
    <div class="flex items-center gap-6 mb-4 text-gray-800 flex-wrap">

        <%= form.search_field :title_cont, 
      placeholder: t('articles.search_placeholder'), 
      class: "h-12 px-6 border border-gray-300 focus:border-primary-400 rounded-md w-72 text-gray-700 placeholder-gray-500 focus:ring-2 focus:ring-primary-50 focus:outline-none transition duration-300" %>

        <%= form.select :status_eq, 
      Visible.VALID_STATUSES.map { |status| [t("visible.valid_statuses.#{status}"), status] }, 
      { include_blank: t('articles.status_placeholder') }, 
      class: "h-12 px-6 border border-gray-300 focus:border-primary-400 rounded-md text-gray-700 bg-white placeholder-gray-500 focus:ring-2 focus:ring-primary-50 focus:outline-none w-72" %>

        <%= form.submit t('shared.search'), 
      class: "h-12 px-6 bg-primary-600 text-white rounded-md hover:bg-primary-500 transition duration-300 focus:outline-none focus:ring-2 focus:ring-primary-light" %>

    </div>
<% end %>

app/views/articles/_table.html.erb
<tr class="hover:bg-primary-200 hover:bg-opacity-10 transition-all duration-200">
    <td class="py-3 px-6 text-sm text-gray-800">
        <%= article.id %>
    </td>
    <td class="py-3 px-6 text-sm text-primary-600">
        <%= link_to article.title, article_path(article), class: "text-primary-600 hover:text-primary-800" %>
    </td>
    <td class="py-3 px-6 text-sm text-gray-800">
        <%= article.body.to_plain_text.truncate(100) %>
    </td>
    <td class="py-3 px-6 text-sm text-gray-800">
        <%= t("visible.valid_statuses.#{article.status}") %>
    </td>
    <td class="py-3 px-6 text-sm text-gray-800">
        <div class="w-6 h-6 border-2 border-primary-600 text-white rounded-full flex items-center justify-center text-xs bg-primary-600 ring-4 ring-primary-100">
            <%= article.user.first_name[0].upcase + article.user.last_name[0].upcase %>
        </div>
    </td>
    <td class="py-3 px-6 text-sm">
        <% if current_user.role_admin? || article.user == current_user %>
            <%= link_to t("actions.edit"), edit_article_path(article), class: "text-primary-600 hover:text-primary-700 transition-colors" %>
            |
            <%= link_to t("actions.destroy"), article_path(article), data: { turbo_method: :delete, turbo_confirm: t("are_you_sure") }, class: "text-primary-600 hover:text-primary-700 transition-colors" %>
        <% end %>
    </td>
</tr>

app/views/articles/edit.html.erb
<section class="max-w-6xl mx-auto p-6 bg-white shadow-lg rounded-lg">
    <h1 class="text-3xl font-bold text-gray-900 mb-6">Edit Article</h1>

    <%= render "form", article: @article %>
</section>

app/views/articles/index.html.erb
<div class="flex flex-col gap-6">
    <div class="bg-white p-8 border border-gray-200 shadow-md rounded-lg">
        <div class="flex flex-col items-center justify-center text-center">
            <h1 class="text-3xl font-extrabold text-secondary-950 mb-4">
                <%= t('articles.title') %>
            </h1>
            <p class="text-lg text-gray-600 mb-6">
                <%= t('articles.subtitle', count: Article.public_count) %>
            </p>
            <div class="w-full flex items-center justify-center">
                <%= render 'search' %>
            </div>
            <%= link_to t('articles.new_article'), new_article_path, 
        class: "mt-3 px-6 py-3 text-sm font-semibold text-white bg-primary-600 hover:bg-primary-500 rounded-lg shadow-md transition duration-300" %>
        </div>
    </div>

    <div id="articles" class="bg-white border border-gray-200 shadow-md rounded-lg p-6">
        <table class="min-w-full table-auto">
            <thead class="bg-gray-50 border-b border-gray-200">
                <tr>
                    <th class="py-4 px-6 text-left text-sm font-semibold text-gray-800">
                        <%= sort_link(@query, :id, 'ID', { class: 'cursor-pointer hover:text-primary-500' }) %>
                    </th>
                    <th class="py-4 px-6 text-left text-sm font-semibold text-gray-800">
                        <%= sort_link(@query, :title, t('table.title'), { class: 'cursor-pointer hover:text-primary-500' }) %>
                    </th>
                    <th class="py-4 px-6 text-left text-sm font-semibold text-gray-800">
                        <%= sort_link(@query, :body, t('table.description'), { class: 'cursor-pointer hover:text-primary-500' }) %>
                    </th>
                    <th class="py-4 px-6 text-left text-sm font-semibold text-gray-800">
                        <%= t('table.status') %>
                    </th>
                    <th class="py-4 px-6 text-left text-sm font-semibold text-gray-800">
                        <%= t('table.author') %>
                    </th>
                    <th class="py-4 px-6 text-left text-sm font-semibold text-gray-800">
                        <%= t('table.actions') %>
                    </th>
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-200">
                <%= render partial: 'articles/table', collection: @articles, as: :article %>
            </tbody>
        </table>
    </div>

    <div class="flex justify-center -mt-5">
        <%== pagy_nav(@pagy, link_extra: 'class="pagination-button bg-primary-600 hover:bg-primary-500 text-white rounded-md px-3 text-sm"') %>
    </div>

</div>

app/views/articles/new.html.erb
<%= form_with model: @article do |form| %>
<section class="bg-white border border-gray-200 shadow-md rounded-lg p-6 mb-6 max-w-6xl mx-auto">
    <div class="mb-4">
        <%= form.label :title, class: "block text-sm font-semibold text-gray-700 mb-2" %>
        <%= form.text_field :title, class: "h-12 px-4 border border-gray-300 rounded-md w-full text-gray-700 placeholder-gray-500 focus:ring-2 focus:ring-primary-50 focus:outline-none" %>
        <% @article.errors.full_messages_for(:title).each do |message| %>
        <div class="text-red-500 text-sm mt-1"><%= message %></div>
        <% end %>
    </div>

    <div class="mb-4">
        <%= form.label :body, class: "block text-sm font-semibold text-gray-700 mb-2" %>
        <%= form.rich_text_area :body, class: "h-48 px-4 border border-gray-300 rounded-md w-full text-gray-700 placeholder-gray-500 focus:ring-2 focus:ring-primary-50 focus:outline-none" %>
        <% @article.errors.full_messages_for(:body).each do |message| %>
        <div class="text-red-500 text-sm mt-1"><%= message %></div>
        <% end %>
    </div>

    <div class="mb-4">
        <%= form.label :status, class: "block text-sm font-semibold text-gray-700 mb-2" %>
        <%= form.select :status, 
                Visible.VALID_STATUSES.map { |status| [t("visible.valid_statuses.#{status}"), status] }, 
                { selected: @article.status || 'public' }, 
               class: "h-12 px-4 border border-gray-300 rounded-md w-full text-gray-700 placeholder-gray-500 focus:ring-2 focus:ring-primary-50 focus:outline-none" %>
    </div>

    <div data-controller="publish-scheduling">
        <div class="mb-4">
            <%= form.check_box :schedule_publish, id: "schedule_publish_checkbox", class: "mr-2", data: { "publish-scheduling-target": "checkbox", action: "change->publish-scheduling#togglePublishAtField" } %>
            <%= form.label :schedule_publish, "Gelecekte Yayınla", class: "text-sm font-semibold text-gray-700" %>
        </div>

        <div class="mb-4">
            <%= form.label :publish_at, "Planlanan Yayın Tarihi", class: "block text-sm font-semibold text-gray-700 mb-2" %>
            <%= form.datetime_local_field :publish_at, class: "h-12 px-4 border border-gray-300 rounded-md w-full text-gray-700 placeholder-gray-500 focus:ring-2 focus:ring-primary-50 focus:outline-none" %>
        </div>

    </div>




    <div class="mb-4">
        <%= form.label :tag_ids, "Etiketler", class: "block text-sm font-semibold text-gray-700 mb-2" %>
        <%= form.collection_select :tag_ids, Tag.all, :id, :name, 
      { include_blank: false }, 
      { multiple: true, size: 5, class: "px-4 border border-gray-300 rounded-md w-full text-gray-700 placeholder-gray-500 focus:ring-2 focus:ring-primary-50 focus:outline-none" } %>
    </div>

    <div class="mb-4">
        <%= form.label :image, "Görsel Yükle", class: "block text-sm font-semibold text-gray-700 mb-2" %>
        <%= form.file_field :image, class: "block w-full text-gray-700 border border-gray-300 rounded-md px-4 py-2 focus:ring-2 focus:ring-primary-50 focus:outline-none" %>
        <% @article.errors.full_messages_for(:image).each do |message| %>
        <div class="text-red-500 text-sm mt-1"><%= message %></div>
        <% end %>
    </div>

    <div>
        <%= form.submit "Save", class: "w-full bg-primary-500 text-white font-bold py-2 rounded-lg hover:bg-primary-600 focus:outline-none focus:ring-2 focus:ring-primary-700 transition duration-200" %>
    </div>
</section>
<% end %>

app/views/articles/show.html.erb
<article class="overflow-hidden">
    <header class="relative">
        <% if @article.image.attached? %>
        <%= image_tag @article.image, class: "w-full h-96 object-cover bg-red-500" %>
        <% else %>
        <img src="https://via.placeholder.com/1200x400" alt="<%= @article.title %>" class="w-full h-96 object-cover" />
        <% end %>
        <div class="absolute inset-0 bg-gradient-to-t from-gray-500 via-transparent to-transparent"></div>
        <div class="absolute bottom-0 left-0 p-8">
            <h1 class="text-4xl md:text-5xl font-extrabold text-white mb-4 leading-tight">
                <%= @article.title %>
            </h1>
            <div class="flex items-center space-x-4">
                <div class="w-9 h-9 border-2 border-primary-600 text-white rounded-full flex items-center justify-center font-semibold text-lg bg-primary-600 ring-4 ring-primary-100" aria-expanded="false">
                    <%= current_user.first_name[0].upcase + current_user.last_name[0].upcase %>
                </div>
                <div>
                    <p class="text-white font-semibold"><%= @article.user.full_name.upcase %></p>
                    <p class="text-gray-300 text-sm"><%= @article.created_at.strftime("%B %d, %Y") %></p>
                </div>
            </div>
        </div>
        <div class="absolute bottom-0 right-0 flex space-x-4 p-8">
            <%= link_to edit_article_path(@article), class: "w-10 h-10 flex items-center justify-center bg-gray-800 text-white rounded-full hover:bg-gray-700 transition duration-200 shadow-md" do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
            </svg>
            <span class="sr-only">Edit</span>
            <% end %>
            <%= link_to article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this article?" },  class: "w-10 h-10 flex items-center justify-center bg-gray-800 text-white rounded-full hover:bg-gray-700 transition duration-200 shadow-md" do %>
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
            </svg>
            <span class="sr-only">Delete</span>
            <% end %>


            <div data-controller="modal">
                <%= link_to new_article_recommendation_path(@article), 
      class: "w-10 h-10 flex items-center justify-center bg-gray-800 text-white rounded-full hover:bg-gray-700 transition duration-200 shadow-md", 
      data: { action: "click->modal#open", turbo_frame: 'modal' } do %>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path d="M8 9a3 3 0 100-6 3 3 0 000 6zM8 11a6 6 0 016 6H2a6 6 0 016-6zM16 7a1 1 0 10-2 0v1h-1a1 1 0 100 2h1v1a1 1 0 102 0v-1h1a1 1 0 100-2h-1V7z" />
                </svg>
                <span class="sr-only">Recommend Article</span>
                <% end %>
            </div>


        </div>
    </header>

    <div class="max-w-7xl mx-auto overflow-hidden">

        <div class="p-4">
            <%= turbo_stream_from "article_#{@article.id}_likes" %>
            <%= turbo_stream_from "likes_count" %>

            <%= render partial: "articles/like_button", formats: [:html], locals: { article: @article } %>
            <%= render partial: "articles/like_count", locals: { article: @article } %>
        </div>


        <div class="flex flex-col lg:flex-row gap-8 p-6">
            <div class="lg:w-3/4">
                <article class="prose lg:prose-lg max-w-none">
                    <div class="article-body">
                        <%= @article.body %>

                        <div data-controller="progress">
                            <div class="fixed bottom-0 z-50 left-0 w-full h-2 bg-gray-200">
                                <div data-progress-target="progress" class="h-2 bg-primary-600 transition-all"></div>
                            </div>
                        </div>

                    </div>
                </article>
            </div>

            <div class="lg:w-1/4" data-controller="toc">
                <div class="sticky top-6 bg-gray-100 p-5 rounded-lg shadow-inner">
                    <h2 class="text-2xl font-bold mb-4 text-gray-800">İçindekiler</h2>
                    <div data-toc-target="toc" class="bg-gray-200 p-4 rounded-lg shadow-inner"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="max-w-7xl mx-auto mt-10 px-4 sm:px-6 lg:px-8">
        <div class="bg-white rounded-xl shadow-sm p-6 border border-gray-100">
            <h2 class="text-2xl font-bold text-gray-800 mb-6 flex items-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
                </svg>
                Comments
            </h2>

            <div class="space-y-6">
                <%= turbo_frame_tag "comments" do %>
                <%= render @article.comments %>
                <% end %>
            </div>

            <div class="mt-8 pt-6 border-t border-gray-100">
                <%= render "comments/form", comment: Comment.new %>
            </div>
        </div>
    </div>


</article>