config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|tr/ do
    devise_for :users, controllers: {
      sessions: "users/authentication/sessions",
      registrations: "users/authentication/registrations"
    }

    devise_scope :user do
      get "profile", to: "users/authentication/registrations#show", as: "user_profile"
      get "/users/sign_out" => "users/authentication/sessions#destroy"
    end

    root "articles#index"

    resources :articles do
      resources :likes, only: [ :create, :destroy ]
      resources :recommendations, only: [ :create, :new ]
      resources :comments, only: [ :create, :destroy ]
      collection do
        get "search", to: "articles#search"
      end
    end

    resources :notifications, only: [ :index ] do
      member do
        post :mark_as_read
      end
    end

    resources :tags, only: [ :index, :show ]

    get "categories", to: "pages#categories"
    get "about", to: "pages#about"
    get "contact", to: "pages#contact"

    get "recommendations", to: "recommendations#index", as: "recommendations"
  end
end

app/views/shared/_article_header.html.erb
<header class="fixed top-0 left-0 right-0 bg-white/60 backdrop-blur-sm shadow-md transition duration-300 z-50" data-controller="header">
    <div class="container mx-auto ">
        <div class="flex items-center justify-between h-16">
            <div class="flex-shrink-0">
                <%= link_to root_path, class: "flex items-center" do %>
                    <span class="sr-only">
                        Blog</span>
                    <span class="text-2xl font-bold text-primary-600">YourBlog</span>
                <% end %>
            </div>

            <nav class="hidden md:flex items-center space-x-12">
                <%= link_to "Anasayfa", root_path, class: "text-secondary-600 hover:text-primary-400 transition duration-100" %>
                <%= link_to "Hakkımda", about_path, class: "text-secondary-600 hover:text-primary-400 transition duration-100" %>
                <%= link_to "İletişim", contact_path, class: "text-secondary-600 hover:text-primary-400 transition duration-100" %>
                <%= link_to "Etiketler", tags_path, class: "text-secondary-600 hover:text-primary-400 transition duration-100" %>
            </nav>

            <div class="hidden md:flex items-center space-x-4">

                <div class="relative" data-controller="dropdown">
                    <button type="button" data-action="click->dropdown#toggle" class="w-9 h-9 border-2 border-primary-600 text-white rounded-full flex items-center justify-center font-semibold text-lg bg-primary-600 ring-4 ring-primary-100" aria-expanded="false">
                        <%= current_user.first_name[0].upcase + current_user.last_name[0].upcase %>

                    </button>
                    <div data-dropdown-target="menu" class="hidden absolute z-10 right-0 transform -translate-x-1 mt-3 w-screen max-w-md" style="position:absolute;">
                        <div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 overflow-hidden backdrop-blur-sm">
                            <div class="relative bg-white dark:bg-gray-800">
                                <div class="px-5 py-3 border-b border-gray-200 dark:border-gray-700">
                                    <h3 class="text-sm font-medium text-gray-700 dark:text-gray-300">Hesap Menüsü</h3>
                                </div>

                                <div class="p-1">
                                    <%= link_to edit_user_registration_path, class: "flex items-center px-4 py-3 hover:bg-gray-50 dark:hover:bg-gray-700 rounded-md transition duration-150 group" do %>
                                        <div class="flex-shrink-0 mr-3">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-500 group-hover:text-primary-500" viewBox="0 0 20 20" fill="currentColor">
                                                <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"/>
                                            </svg>
                                        </div>
                                        <div>
                                            <p class="text-sm font-medium text-gray-700 dark:text-gray-300 group-hover:text-primary-500">Profili Düzenle</p>
                                            <p class="text-xs text-gray-500 dark:text-gray-400">Hesap bilgilerinizi güncelleyin</p>
                                        </div>
                                    <% end %>

                                    <%= link_to notifications_path, data: { action: "click->modal#open", turbo: true, turbo_frame: 'modal' } do %>
                                        <%= turbo_frame_tag "notification_count", data: { turbo_permanent: true } do %>
                                            <%= render "notifications/notification_count", user: current_user %>
                                        <% end %>
                                    <% end %>

                                    <%= turbo_stream_from "notification_count_#{current_user.id}" %>

                                    <div class="my-1 border-t border-gray-200 dark:border-gray-700"></div>

                                    <%= link_to destroy_user_session_path, method: :delete, data: { turbo: false }, class: "flex items-center px-4 py-3 hover:bg-gray-50 dark:hover:bg-gray-700 rounded-md transition duration-150 group text-red-500 hover:text-red-600" do %>
                                        <div class="flex-shrink-0 mr-3">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                                <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                                                <polyline points="16 17 21 12 16 7"></polyline>
                                                <line x1="21" y1="12" x2="9" y2="12"></line>
                                            </svg>
                                        </div>
                                        <p class="text-sm font-medium">Çıkış Yap</p>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="-mr-2 flex md:hidden">
                <button data-action="click->header#toggleMenu" type="button" class="bg-white inline-flex items-center justify-center p-2 rounded-md text-secondary-400 hover:text-secondary-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-primary-500" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>
                    <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <div data-header-target="mobileMenu" class="hidden md:hidden bg-white w-full h-full" style="position:absolute;">
        <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
            <%= link_to "Anasayfa", root_path, class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
            <%= link_to "Kategoriler", categories_path, class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
            <%= link_to "Hakkımda", about_path, class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
            <%= link_to "İletişim", contact_path, class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
        </div>
        <div class="pt-4 pb-3 border-t border-gray-200">
            <div class="px-2 space-y-1">
                <% if user_signed_in? %>
                    <%= link_to 'Edit Profile', edit_user_registration_path , class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
                    <%= link_to 'Logout', destroy_user_session_path , method: :delete, data: { turbo: false }, class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
                <% else %>
                    <%= link_to 'Login', new_user_session_path, class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
                    <%= link_to 'Sign Up', new_user_registration_path, class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
                <% end %>
            </div>
        </div>
    </div>
</header>

app/views/shared/_header.html.erb
<header class="bg-white shadow-md " data-controller="header">
    <div class="container mx-auto ">
        <div class="flex items-center justify-between h-16">
            <div class="flex-shrink-0">
                <%= link_to root_path, class: "flex items-center" do %>
                    <span class="sr-only">
                        Blog</span>
                    <span class="text-2xl font-bold text-primary-600">YourBlog</span>
                <% end %>
            </div>

            <nav class="hidden md:flex items-center space-x-12">
                <%= link_to "Anasayfa", root_path, class: "text-secondary-600 hover:text-primary-400 transition duration-100" %>
                <%= link_to "Hakkımda", about_path, class: "text-secondary-600 hover:text-primary-400 transition duration-100" %>
                <%= link_to "İletişim", contact_path, class: "text-secondary-600 hover:text-primary-400 transition duration-100" %>
                <%= link_to "Etiketler", tags_path, class: "text-secondary-600 hover:text-primary-400 transition duration-100" %>
            </nav>

            <div class="hidden md:flex items-center space-x-4">

                <div class="relative" data-controller="dropdown">
                    <button type="button" data-action="click->dropdown#toggle" class="w-9 h-9 border-2 border-primary-600 text-white rounded-full flex items-center justify-center font-semibold text-lg bg-primary-600 ring-4 ring-primary-100" aria-expanded="false">
                        <%= current_user.first_name[0].upcase + current_user.last_name[0].upcase %>

                    </button>
                    <div data-dropdown-target="menu" class="hidden absolute z-10 right-0 transform -translate-x-1 mt-3 w-screen max-w-md" style="position:absolute;">
                        <div class="rounded-lg shadow-lg ring-1 ring-black ring-opacity-5 overflow-hidden backdrop-blur-sm">
                            <div class="relative bg-white dark:bg-gray-800">
                                <div class="px-5 py-3 border-b border-gray-200 dark:border-gray-700">
                                    <h3 class="text-sm font-medium text-gray-700 dark:text-gray-300">Hesap Menüsü</h3>
                                </div>

                                <div class="p-1">
                                    <%= link_to edit_user_registration_path, class: "flex items-center px-4 py-3 hover:bg-gray-50 dark:hover:bg-gray-700 rounded-md transition duration-150 group" do %>
                                        <div class="flex-shrink-0 mr-3">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 text-gray-500 group-hover:text-primary-500" viewBox="0 0 20 20" fill="currentColor">
                                                <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"/>
                                            </svg>
                                        </div>
                                        <div>
                                            <p class="text-sm font-medium text-gray-700 dark:text-gray-300 group-hover:text-primary-500">Profili Düzenle</p>
                                            <p class="text-xs text-gray-500 dark:text-gray-400">Hesap bilgilerinizi güncelleyin</p>
                                        </div>
                                    <% end %>

                                    <%= link_to notifications_path, data: { action: "click->modal#open", turbo: true, turbo_frame: 'modal' } do %>
                                        <%= turbo_frame_tag "notification_count", data: { turbo_permanent: true } do %>
                                            <%= render "notifications/notification_count", user: current_user %>
                                        <% end %>
                                    <% end %>

                                    <%= turbo_stream_from "notification_count_#{current_user.id}" %>

                                    <div class="my-1 border-t border-gray-200 dark:border-gray-700"></div>

                                    <%= link_to destroy_user_session_path, method: :delete, data: { turbo: false }, class: "flex items-center px-4 py-3 hover:bg-gray-50 dark:hover:bg-gray-700 rounded-md transition duration-150 group text-red-500 hover:text-red-600" do %>
                                        <div class="flex-shrink-0 mr-3">
                                            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                                <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                                                <polyline points="16 17 21 12 16 7"></polyline>
                                                <line x1="21" y1="12" x2="9" y2="12"></line>
                                            </svg>
                                        </div>
                                        <p class="text-sm font-medium">Çıkış Yap</p>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>


            <div class="-mr-2 flex md:hidden">
                <button data-action="click->header#toggleMenu" type="button" class="bg-white inline-flex items-center justify-center p-2 rounded-md text-secondary-400 hover:text-secondary-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-primary-500" aria-expanded="false">
                    <span class="sr-only">Open main menu</span>
                    <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"/>
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <div data-header-target="mobileMenu" class="hidden md:hidden bg-white w-full h-full" style="position:absolute;">
        <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
            <%= link_to "Anasayfa", root_path, class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
            <%= link_to "Kategoriler", categories_path, class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
            <%= link_to "Hakkımda", about_path, class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
            <%= link_to "İletişim", contact_path, class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
        </div>
        <div class="pt-4 pb-3 border-t border-gray-200">
            <div class="px-2 space-y-1">
                <% if user_signed_in? %>
                    <%= link_to 'Edit Profile', edit_user_registration_path , class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
                    <%= link_to 'Logout', destroy_user_session_path , method: :delete, data: { turbo: false }, class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
                <% else %>
                    <%= link_to 'Login', new_user_session_path, class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
                    <%= link_to 'Sign Up', new_user_registration_path, class: "block px-3 py-2 rounded-md text-base font-medium text-secondary-600 hover:text-primary-400 hover:bg-gray-50" %>
                <% end %>
            </div>
        </div>
    </div>
</header>

app/views/shared/_lang.html.erb
<div class="flex justify-center items-center gap-6 p-2">
    <% [:en, :tr].each do |locale| %>
        <% if locale != I18n.locale %>
            <%= link_to locale.to_s.upcase, request.params.merge(locale: locale), 
        class: "px-6 py-2 rounded-full bg-secondary-500 text-white hover:bg-primary-600 hover:text-white transition duration-300" %>
        <% end %>
    <% end %>
</div>

app/views/shared/_modal.html.erb
<div class="fixed inset-0 bg-white bg-opacity-50 backdrop-blur-md flex items-center justify-center z-50 hidden" data-controller="modal" data-modal-target="parent">
    <div class="bg-white rounded-2xl w-full max-w-3xl lg:max-w-4xl mx-4 sm:mx-0 shadow-lg">
        <div class="flex justify-end p-4">
            <button type="button" class="text-gray-500 hover:text-gray-700 text-3xl" data-action="modal#close" aria-label="Close">
                &times;
            </button>
        </div>
        <div class="p-6 space-y-6 text-gray-700">
            <%= turbo_frame_tag 'modal', data: { "modal-target": "frame", "action": "turbo:frame-load->modal#open" } do %><% end %>
        </div>
    </div>
</div>